apiVersion: v1
kind: Service
metadata:
  name: nginx-alb
  namespace: nginx-http
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    alb.ingress.kubernetes.io/target-type: "instance"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-pod
  externalIPs:
    - 52.60.199.226
    - 15.156.229.30
