apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-http
  labels:
    svc: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx-app
    # This will route all traffic to dev pod
    env: dev
  ports:
    - port: 80
      targetPort: 80