# k expose pod/nginx-pod -n nginx-http --type=NodePort --port=80 --target-port=80
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-http
  # labels:
  #   app: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80